language: php

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
